POST http://localhost:3000/v2/users/login
Content-Type: application/json

{
    "fullName":"Serhii"
}

###
DELETE  http://localhost:3000/v2/users/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImZ1bGxOYW1lIjoiU2VyaGlpIn0sImlhdCI6MTU4NTI2ODI0NywiZXhwIjoxNTg1MzU0NjQ3fQ.oFUzIcMkvJ8L_D5diUyi9aQtQ7Za1t1nWEtT8QWiBtM"
}

###
POST http://localhost:3000/v2/users/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImZ1bGxOYW1lIjoiU2VyaGlpIn0sImlhdCI6MTU4NTI2ODI0NywiZXhwIjoxNTg1MzU0NjQ3fQ.oFUzIcMkvJ8L_D5diUyi9aQtQ7Za1t1nWEtT8QWiBtM"
}
###

GET http://localhost:3000/v2/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImZ1bGxOYW1lIjoiU2VyaGlpIn0sImlhdCI6MTU4NTI2ODk0MCwiZXhwIjoxNTg1MjY5MjQwfQ.5G9T6J1qyIQ_iW_CPYMco4iNGCB8MHMMmsvKFr3RUM8
